#!/usr/bin/env python
import sys
x = int(raw_input('x='))
y = int(raw_input('y='))
n = max(x,y) + 1
X = divmod(n,x)
Y = divmod(n,y)
while n <= x * y:
    if X[-1] == 0 and Y[-1] == 0:
        print n
        sys.exit()
    else:
        n += 1
        X = divmod(n,x)
        Y = divmod(n,y)
print 'none'